name = "gudangbuku"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages Static Build Output Directory
pages_build_output_dir = "tokobuku-v2"

# Cloudflare D1 Database Binding Configuration
# Binds the database instance to context.env.DB in Cloudflare Pages Functions
[[d1_databases]]
binding = "DB"
database_name = "gudangbuku-db"
database_id = "gudangbuku-db"
